#ifndef MLTCONTROLLER_GLOBAL_H
#define MLTCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MLTCONTROLLER_LIBRARY)
#  define MLTCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MLTCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MLTCONTROLLER_GLOBAL_H
