#ifndef QMLUTILITIES_GLOBAL_H
#define QMLUTILITIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMLUTILITIES_LIBRARY)
#  define QMLUTILITIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMLUTILITIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMLUTILITIES_GLOBAL_H
