#ifndef PLAYLISTDOCK_GLOBAL_H
#define PLAYLISTDOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAYLISTDOCK_LIBRARY)
#  define PLAYLISTDOCKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLAYLISTDOCKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAYLISTDOCK_GLOBAL_H
