#ifndef UIUSERDEF_H
#define UIUSERDEF_H

#define LISTVIEW_GRIDSIZE_WIDTH 140
#define LISTVIEW_GRIDSIZE_HEIGHT 120
#define LISTVIEW_GRID_SPACING 5
#define LISTVIEW_ITEMICONSIZE_WIDTH 120
#define LISTVIEW_ITEMICONSIZE_HEIGHT 80
#define LISTVIEW_ITEM_ADDBTNSIZE 30
#define LISTVIEW_ITEM_FONTSIZE 8

// stickerdock的动画下拉列表宽度
#define ANIMATION_COMBOBOX_WIDTH 160

#endif // UIUSERDEF_H
