#ifndef EFFECTDOCK_GLOBAL_H
#define EFFECTDOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EFFECTDOCK_LIBRARY)
#  define EFFECTDOCKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EFFECTDOCKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EFFECTDOCK_GLOBAL_H
