#ifndef AUDIOFILTERDOCK_GLOBAL_H
#define AUDIOFILTERDOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUDIOFILTERDOCK_LIBRARY)
#  define AUDIOFILTERDOCKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUDIOFILTERDOCKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUDIOFILTERDOCK_GLOBAL_H
