#ifndef TEMPLATEEDITORDOCK_GLOBAL_H
#define TEMPLATEEDITORDOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEMPLATEEDITORDOCK_LIBRARY)
#  define TEMPLATEEDITORDOCKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEMPLATEEDITORDOCKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPLATEEDITORDOCK_GLOBAL_H
