#ifndef TEMPLATEDOCK_GLOBAL_H
#define TEMPLATEDOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEMPLATEDOCK_LIBRARY)
#  define TEMPLATEDOCKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEMPLATEDOCKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPLATEDOCK_GLOBAL_H
