#ifndef FILTERDOCK_GLOBAL_H
#define FILTERDOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILTERDOCK_LIBRARY)
#  define FILTERDOCKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILTERDOCKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERSELECTDOCK_GLOBAL_H
