#ifndef COMMONUTIL_GLOBAL_H
#define COMMONUTIL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONUTIL_LIBRARY)
#  define COMMONUTILSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMONUTILSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONUTIL_GLOBAL_H
