#ifndef CONFIGURATIONDOCK_GLOBAL_H
#define CONFIGURATIONDOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONFIGURATIONDOCK_LIBRARY)
#  define CONFIGURATIONDOCKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONFIGURATIONDOCKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONFIGURATIONDOCK_GLOBAL_H
